name: flutter_bloc_base
description: Flutter application with Bloc Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Lint rule
  pedantic: ^1.9.2

  equatable: ^1.2.5
  # Resource localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.1
  flutter_bloc: ^8.1.0
  shared_preferences: ^2.0.15
  sqflite: ^2.2.0+3
  permission_handler: ^10.2.0
  connectivity: ^3.0.6
  carousel_slider: ^2.3.1
  cached_network_image: ^2.5.0
  http: ^0.13.5
  shape_of_view: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  mockito: ^5.2.0
#  integration_test: ^1.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  # Generation resource
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
        - asset: assets/fonts/Muli-SemiBold.ttf
        - asset: assets/fonts/Muli-Regular.ttf
